mpc:
  N_horizon: 100 # Prediction steps
  tf: 1.0 # Prediction horizon in seconds
  Q: [5.0, 5.0, 10.0, 0.1, 0.1, 20.0, 0.0, 0.0, 0.0] # Weight for internal states: [x, y, z, roll, pitch, yaw, vx, vy, vz]
  Qe: [10.0, 10.0, 20.0, 0.1, 0.1, 20.0, 0.0, 0.0, 0.0] # Weight for end states: [x, y, z, roll, pitch, yaw, vx, vy, vz]
  R: [0.8, 1.0, 1.0, 0.5] # Weight for control inputs: [thrust, wx, wy, wz]
  lbu: [0.01, -5.0, -5.0, -5.0] # Lower bounds for control inputs: [thrust, wx, wy, wz]
  ubu: [40.0, 5.0, 5.0, 5.0] # Upper bounds for control inputs: [thrust, wx, wy, wz]
  idxbx: [7, 8, 9] # Indexes for state bounds: [vx, vy, vz]
  lbx: [0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,-3.0,-3.0] # Lower bounds for internal states: [vx, vy, vz]
  ubx: [0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,3.0] # Uper bounds for internal states: [vx, vy, vz]
  p: [1.0, 1.0, 0.0, 0.0, 0.0] # Online parameter: [mass, qw_ref, qx_ref, qy_ref, qz_ref]        