sim_config:
  sim_time: 20.0 # s
  dt: 0.01 # s
  trajectory_generator_max_speed: 2.0 # m/s
  trajectory_generator_waypoints:
  - [ 0.0,  0.0, 1.0]
  - [ 2.0, -2.0, 2.0]
  - [ 2.0,  2.0, 2.0]
  - [-2.0, -2.0, 2.0]
  - [-2.0,  2.0, 2.0]
  - [ 0.0,  0.0, 2.0]
  path_facing: True