// Copyright 2024 Universidad Politécnica de Madrid
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//    * Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//    * Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//
//    * Neither the name of the Universidad Politécnica de Madrid nor the names of its
//      contributors may be used to endorse or promote products derived from
//      this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.

/**
 * @file acados_mpc_datatype.hpp
 *
 * Acados MPC data types definition.
 *
 * @author Rafael Perez-Segui <r.psegui@upm.es>
 */

#ifndef ACADOS_MPC_ACADOS_MPC_DATATYPE_HPP_
#define ACADOS_MPC_ACADOS_MPC_DATATYPE_HPP_

#include <mpc_generated_code/acados_sim_solver_mpc_position.h>
#include <mpc_generated_code/acados_solver_mpc_position.h>
#include <mpc_generated_code/mpc_position_model/mpc_position_model.h>

#include <array>
#include <stdexcept>
#include <string>

namespace acados_mpc {

/**
 * @brief State x
 */
struct State {
  static constexpr size_t Nx = MPC_POSITION_NX;
  std::array<double, MPC_POSITION_NX> data;
  static const std::size_t size                  = MPC_POSITION_NX;
  static constexpr size_t position_offset        = 0;
  static constexpr size_t position_length        = 3;
  static constexpr size_t orientation_offset     = 3;
  static constexpr size_t orientation_length     = 4;
  static constexpr size_t linear_velocity_offset = 7;
  static constexpr size_t linear_velocity_length = 3;

  /**
   * @brief Constructor
   */
  State();

  /**
   * @brief Set the data at index
   *
   * @param index index.
   * @param value value.
   */
  void setData(const int index, const double value);
  /**
   * @brief Position in world frame [x, y, z] (m)
   *
   * @param value position value.
   */
  void setPosition(const std::array<double, position_length>& value);

  /**
   * @brief Position in world frame [x, y, z] (m)
   *
   * @return std::array<double, position_length> position value.
   */
  std::array<double, position_length> getPosition() const;
  /**
   * @brief Orientation of the body frame in world frame as a quaternion [qw, qx, qy, qz]
   *
   * @param value orientation value.
   */
  void setOrientation(const std::array<double, orientation_length>& value);

  /**
   * @brief Orientation of the body frame in world frame as a quaternion [qw, qx, qy, qz]
   *
   * @return std::array<double, orientation_length> orientation value.
   */
  std::array<double, orientation_length> getOrientation() const;
  /**
   * @brief Linear velocity in world frame [vx, vy, vz] (m/s)
   *
   * @param value linear_velocity value.
   */
  void setLinearVelocity(const std::array<double, linear_velocity_length>& value);

  /**
   * @brief Linear velocity in world frame [vx, vy, vz] (m/s)
   *
   * @return std::array<double, linear_velocity_length> linear_velocity value.
   */
  std::array<double, linear_velocity_length> getLinearVelocity() const;
};

/**
 * @brief Actuation u
 */
struct Actuation {
  static constexpr size_t Nu = MPC_POSITION_NU;
  std::array<double, MPC_POSITION_NU> data;
  static const std::size_t size                   = MPC_POSITION_NU;
  static constexpr size_t thrust_offset           = 0;
  static constexpr size_t thrust_length           = 1;
  static constexpr size_t angular_velocity_offset = 1;
  static constexpr size_t angular_velocity_length = 3;

  /**
   * @brief Constructor
   */
  Actuation();

  /**
   * @brief Set the data at index
   *
   * @param index index.
   * @param value value.
   */
  void setData(const int index, const double value);
  /**
   * @brief Total thrust generated by the motors (N)
   *
   * @param value thrust value.
   */
  void setThrust(const double value);

  /**
   * @brief Total thrust generated by the motors (N)
   *
   * @return double thrust value.
   */
  double getThrust() const;
  /**
   * @brief Angular velocity in body frame [wx, wy, wz] (rad/s)
   *
   * @param value angular_velocity value.
   */
  void setAngularVelocity(const std::array<double, angular_velocity_length>& value);

  /**
   * @brief Angular velocity in body frame [wx, wy, wz] (rad/s)
   *
   * @return std::array<double, angular_velocity_length> angular_velocity value.
   */
  std::array<double, angular_velocity_length> getAngularVelocity() const;
};

/**
 * @brief Reference yref
 */
struct Reference {
  static constexpr size_t Nyref = MPC_POSITION_NY;
  std::array<double, MPC_POSITION_N * MPC_POSITION_NY> data;
  static const std::size_t size = MPC_POSITION_N * MPC_POSITION_NY;

  /**
   * @brief Constructor
   */
  Reference();

  /**
   * @brief Get the data at index
   *
   * @param index index of the stage.
   * @return double* data.
   */
  double* getData(const int index);

  /**
   * @brief Get the data at index
   *
   * @param index index of the stage.
   * @return const double* data.
   */
  const double* getData(const int index) const;

  /**
   * @brief Set the data at index
   *
   * @param index index of the stage.
   * @param state state.
   */
  void setData(const int index, const double value);

  /**
   * @brief Set the data at index of the stage and value
   *
   * @param ref_index index of the stage.
   * @param value_index index of the value.
   * @param state state.
   */
  void setData(const int ref_index, const int value_index, const double value);
};

struct ReferenceEnd {
  std::array<double, MPC_POSITION_NYN> data;
  static const std::size_t size = MPC_POSITION_NYN;

  /**
   * @brief Constructor
   */
  ReferenceEnd();

  /**
   * @brief Get the data
   *
   * @return double* data.
   */
  double* getData();

  /**
   * @brief Get the data
   *
   * @return const double* data.
   */
  const double* getData() const;

  /**
   * @brief Set the data at index
   *
   * @param index index.
   * @param value value.
   */
  void setData(const int index, const double value);
};

/**
 * @brief Gains
 *
 * Gains Q, R and Qe for the MPC.
 */
struct Gains {
  static constexpr size_t Nq  = MPC_POSITION_NYN;
  static constexpr size_t Nqe = MPC_POSITION_NYN;
  static constexpr size_t Nr  = (MPC_POSITION_NY - MPC_POSITION_NYN);
  std::array<double, MPC_POSITION_NY * MPC_POSITION_NY> W;
  std::array<double, MPC_POSITION_NYN * MPC_POSITION_NYN> We;

  /**
   * @brief Constructor
   */
  Gains();

  /**
   * @brief Get the W matrix
   *
   * @return double* W.
   */
  double* getW();

  /**
   * @brief Get the W matrix
   *
   * @return const double* W.
   */
  const double* getW() const;

  /**
   * @brief Get the We matrix
   *
   * @return double* We.
   */
  double* getWe();

  /**
   * @brief Get the We matrix
   *
   * @return const double* We.
   */
  const double* getWe() const;

  /**
   * @brief Get the Q matrix
   *
   * @return std::array<double, Gains::Nq> Copy of Q.
   */
  std::array<double, Gains::Nq> getQ() const;

  /**
   * @brief Get the Qe matrix
   *
   * @return std::array<double, Gains::Nqe> Copy of Qe.
   */
  std::array<double, Gains::Nqe> getQEnd() const;

  /**
   * @brief Get the R matrix
   *
   * @return std::array<double, Gains::Nr> Copy of R.
   */
  std::array<double, Gains::Nr> getR() const;

  /**
   * @brief Set the W matrix at index
   *
   * @param index index of the diagonal.
   * @param value value.
   */
  void setW(const int index, const double value);

  /**
   * @brief Set the We matrix at index
   *
   * @param index index of the diagonal.
   * @param value value.
   */
  void setWe(const int index, const double value);

  /**
   * @brief Set the Q, Qe and R matrix
   *
   * @param index index of the diagonal.
   * @param value value.
   */
  void setGains(const Gains& gains);

  /**
   * @brief Set the Q matrix at index
   *
   * @param index index of the diagonal.
   * @param value value.
   */
  void setQ(const int index, const double value);

  /**
   * @brief Set the Q matrix
   *
   * @param Q std::array<double, Gains::Nq> Q.
   */
  void setQ(const std::array<double, Gains::Nq>& Q);

  /**
   * @brief Set the R matrix at index
   *
   * @param index index of the diagonal.
   * @param value value.
   */
  void setR(const int index, const double value);

  /**
   * @brief Set the R matrix
   *
   * @param R std::array<double, Gains::Nr> R.
   */
  void setR(const std::array<double, Gains::Nr>& R);

  /**
   * @brief Set the Qe matrix at index
   *
   * @param index index of the diagonal.
   * @param value value.
   */
  void setQEnd(const int index, const double value);

  /**
   * @brief Set the Qe matrix
   *
   * @param Qe std::array<double, Gains::Nqe> Qe.
   */
  void setQEnd(const std::array<double, Gains::Nqe>& Qe);
};

/**
 * @brief ActuationBounds
 *
 * ActuationBounds lbu and ubu for the MPC.
 */
struct ActuationBounds {
  static constexpr size_t Nu = MPC_POSITION_NU;
  std::array<double, MPC_POSITION_NU> lbu;
  std::array<double, MPC_POSITION_NU> ubu;

  /**
   * @brief Constructor
   */
  ActuationBounds();

  /**
   * @brief Get the lbu array
   *
   * @return double* lbu.
   */
  double* getLbu();

  /**
   * @brief Get the lbu array
   *
   * @return const double* lbu.
   */
  const double* getLbu() const;

  /**
   * @brief Get the lbu array
   *
   * @return std::array<double, MPC_POSITION_NU> lbu.
   */
  std::array<double, MPC_POSITION_NU> getLbuArray() const;

  /**
   * @brief Get the ubu array
   *
   * @return double* ubu.
   */
  double* getUbu();

  /**
   * @brief Get the ubu array
   *
   * @return const double* ubu.
   */
  const double* getUbu() const;

  /**
   * @brief Get the ubu array
   *
   * @return std::array<double, MPC_POSITION_NU> ubu.
   */
  std::array<double, MPC_POSITION_NU> getUbuArray() const;

  /**
   * @brief Set the bounds
   *
   * @param bounds bounds.
   */
  void setBounds(const ActuationBounds& bounds);

  /**
   * @brief Set the lbu
   *
   * @param lbu lbu.
   */
  void setLbu(const std::array<double, MPC_POSITION_NU>& lbu);

  /**
   * @brief Set the lbu at index
   *
   * @param index index.
   * @param value value.
   */
  void setLbu(const int index, const double value);

  /**
   * @brief Set the ubu
   *
   * @param ubu ubu.
   */
  void setUbu(const std::array<double, MPC_POSITION_NU>& ubu);

  /**
   * @brief Set the ubu at index
   *
   * @param index index.
   * @param value value.
   */
  void setUbu(const int index, const double value);
};

/**
 * @brief StateBounds
 *
 * StateBounds lbx and ubx for the MPC.
 */
struct StateBounds {
  static constexpr size_t Nx = MPC_POSITION_NBX;
  std::array<double, MPC_POSITION_NBX> lbx;
  std::array<double, MPC_POSITION_NBX> ubx;

  /**
   * @brief Constructor
   */
  StateBounds();

  /**
   * @brief Get the lbx array
   *
   * @return double* lbx.
   */
  double* getLbx();

  /**
   * @brief Get the lbx array
   *
   * @return const double* lbx.
   */
  const double* getLbx() const;

  /**
   * @brief Get the lbx array
   *
   * @return std::array<double, MPC_POSITION_NBX> lbx.
   */
  std::array<double, MPC_POSITION_NBX> getLbxArray() const;

  /**
   * @brief Get the ubx array
   *
   * @return double* ubx.
   */
  double* getUbx();

  /**
   * @brief Get the ubx array
   *
   * @return const double* ubx.
   */
  const double* getUbx() const;

  /**
   * @brief Get the ubx array
   *
   * @return std::array<double, MPC_POSITION_NBX> ubx.
   */
  std::array<double, MPC_POSITION_NBX> getUbxArray() const;

  /**
   * @brief Set the bounds
   *
   * @param bounds bounds.
   */
  void setBounds(const StateBounds& bounds);

  /**
   * @brief Set the lbx
   *
   * @param lbx lbx.
   */
  void setLbx(const std::array<double, MPC_POSITION_NBX>& lbx);

  /**
   * @brief Set the lbx at index
   *
   * @param index index.
   * @param value value.
   */
  void setLbx(const int index, const double value);

  /**
   * @brief Set the ubx
   *
   * @param ubx ubx.
   */
  void setUbx(const std::array<double, MPC_POSITION_NBX>& ubx);

  /**
   * @brief Set the ubx at index
   *
   * @param index index.
   * @param value value.
   */
  void setUbx(const int index, const double value);
};

/**
 * @brief Parameters
 *
 * Online parameters p for one MPC stage.
 */
struct Parameters {
  static constexpr size_t Np = MPC_POSITION_NP;
  std::array<double, MPC_POSITION_NP> data;
  static const std::size_t size                      = MPC_POSITION_NP;
  static constexpr size_t mass_offset                = 0;
  static constexpr size_t mass_length                = 1;
  static constexpr size_t desired_position_offset    = 1;
  static constexpr size_t desired_position_length    = 3;
  static constexpr size_t desired_orientation_offset = 4;
  static constexpr size_t desired_orientation_length = 4;
  static constexpr size_t external_force_offset      = 8;
  static constexpr size_t external_force_length      = 3;
  static constexpr size_t Q_offset                   = 11;
  static constexpr size_t Q_length                   = 9;
  static constexpr size_t Qe_offset                  = 20;
  static constexpr size_t Qe_length                  = 9;
  static constexpr size_t R_offset                   = 29;
  static constexpr size_t R_length                   = 4;

  /**
   * @brief Constructor
   */
  Parameters();

  /**
   * @brief Get the data
   *
   * @return double* data.
   */
  double* getData();

  /**
   * @brief Get the data
   *
   * @return const double* data.
   */
  const double* getData() const;

  /**
   * @brief Get the stage parameters
   *
   * @return std::array<double, MPC_POSITION_NP> Copy of the stage parameters.
   */
  std::array<double, MPC_POSITION_NP> getParameters() const;

  /**
   * @brief Copy parameters from another stage parameter object.
   *
   * @param params parameters to copy.
   */
  void setParameters(const Parameters& params);

  /**
   * @brief Set the data at index
   *
   * @param index index.
   * @param value value.
   */
  void setData(const int index, const double value);
  /**
   * @brief Mass of the MAV (kg)
   *
   * @param value mass value.
   */
  void setMass(const double value);

  /**
   * @brief Mass of the MAV (kg)
   *
   * @return double mass value.
   */
  double getMass() const;
  /**
   * @brief Desired position in world frame [x, y, z] (m)
   *
   * @param value desired_position value.
   */
  void setDesiredPosition(const std::array<double, desired_position_length>& value);

  /**
   * @brief Desired position in world frame [x, y, z] (m)
   *
   * @return std::array<double, desired_position_length> desired_position value.
   */
  std::array<double, desired_position_length> getDesiredPosition() const;
  /**
   * @brief Desired orientation as a quaternion [qw, qx, qy, qz]
   *
   * @param value desired_orientation value.
   */
  void setDesiredOrientation(const std::array<double, desired_orientation_length>& value);

  /**
   * @brief Desired orientation as a quaternion [qw, qx, qy, qz]
   *
   * @return std::array<double, desired_orientation_length> desired_orientation value.
   */
  std::array<double, desired_orientation_length> getDesiredOrientation() const;
  /**
   * @brief External force acting on the MAV in base frame [fx, fy, fz] (N)
   *
   * @param value external_force value.
   */
  void setExternalForce(const std::array<double, external_force_length>& value);

  /**
   * @brief External force acting on the MAV in base frame [fx, fy, fz] (N)
   *
   * @return std::array<double, external_force_length> external_force value.
   */
  std::array<double, external_force_length> getExternalForce() const;
  /**
   * @brief Stage gains for [x, y, z, roll, pitch, yaw, vx, vy, vz]
   *
   * @param value Q value.
   */
  void setQ(const std::array<double, Q_length>& value);

  /**
   * @brief Stage gains for [x, y, z, roll, pitch, yaw, vx, vy, vz]
   *
   * @return std::array<double, Q_length> Q value.
   */
  std::array<double, Q_length> getQ() const;
  /**
   * @brief Terminal gains for [x, y, z, roll, pitch, yaw, vx, vy, vz]
   *
   * @param value Qe value.
   */
  void setQe(const std::array<double, Qe_length>& value);

  /**
   * @brief Terminal gains for [x, y, z, roll, pitch, yaw, vx, vy, vz]
   *
   * @return std::array<double, Qe_length> Qe value.
   */
  std::array<double, Qe_length> getQe() const;
  /**
   * @brief Stage gains for control inputs [thrust, wx, wy, wz]
   *
   * @param value R value.
   */
  void setR(const std::array<double, R_length>& value);

  /**
   * @brief Stage gains for control inputs [thrust, wx, wy, wz]
   *
   * @return std::array<double, R_length> R value.
   */
  std::array<double, R_length> getR() const;
};

/**
 * @brief OnlineParameters
 *
 * Online parameters p for all MPC stages.
 */
struct OnlineParameters {
  using StageParameters           = Parameters;
  static constexpr size_t Np      = MPC_POSITION_NP;
  static constexpr size_t Nstages = MPC_POSITION_N + static_cast<size_t>(1);
  std::array<double, Nstages * MPC_POSITION_NP> data;
  static const std::size_t size                      = Nstages * MPC_POSITION_NP;
  static constexpr size_t mass_offset                = Parameters::mass_offset;
  static constexpr size_t mass_length                = Parameters::mass_length;
  static constexpr size_t desired_position_offset    = Parameters::desired_position_offset;
  static constexpr size_t desired_position_length    = Parameters::desired_position_length;
  static constexpr size_t desired_orientation_offset = Parameters::desired_orientation_offset;
  static constexpr size_t desired_orientation_length = Parameters::desired_orientation_length;
  static constexpr size_t external_force_offset      = Parameters::external_force_offset;
  static constexpr size_t external_force_length      = Parameters::external_force_length;
  static constexpr size_t Q_offset                   = Parameters::Q_offset;
  static constexpr size_t Q_length                   = Parameters::Q_length;
  static constexpr size_t Qe_offset                  = Parameters::Qe_offset;
  static constexpr size_t Qe_length                  = Parameters::Qe_length;
  static constexpr size_t R_offset                   = Parameters::R_offset;
  static constexpr size_t R_length                   = Parameters::R_length;

  /**
   * @brief Constructor
   */
  OnlineParameters();

  /**
   * @brief Get the flattened data
   *
   * @return double* data.
   */
  double* getData();

  /**
   * @brief Get the flattened data
   *
   * @return const double* data.
   */
  const double* getData() const;

  /**
   * @brief Get the data of one stage
   *
   * @param stage stage index.
   * @return double* data.
   */
  double* getData(const int stage);

  /**
   * @brief Get the data of one stage
   *
   * @param stage stage index.
   * @return const double* data.
   */
  const double* getData(const int stage) const;

  /**
   * @brief Get the parameters of one stage
   *
   * @param stage stage index.
   * @return StageParameters Copy of the stage parameters.
   */
  StageParameters getParameters(const int stage = 0) const;

  /**
   * @brief Get all online parameters flattened by stage
   *
   * @return std::array<double, Nstages * MPC_POSITION_NP> Copy of online parameters.
   */
  std::array<double, Nstages * MPC_POSITION_NP> getOnlineParameters() const;

  /**
   * @brief Copy all online parameters.
   *
   * @param params online parameters to copy.
   */
  void setParameters(const OnlineParameters& params);

  /**
   * @brief Set the parameters of one stage or all stages.
   *
   * @param params stage parameters.
   * @param stage stage index, or -1 to apply to all stages.
   */
  void setParameters(const StageParameters& params, const int stage = -1);

  /**
   * @brief Set flattened data at index
   *
   * @param index index.
   * @param value value.
   */
  void setData(const int index, const double value);

  /**
   * @brief Set the data at stage index and parameter index.
   *
   * @param stage stage index.
   * @param index parameter index within the stage.
   * @param value value.
   */
  void setData(const int stage, const int index, const double value);
  /**
   * @brief Mass of the MAV (kg)
   *
   * @param value mass value.
   * @param stage stage index, or -1 to apply to all stages.
   */
  void setMass(const double value, const int stage = -1);

  /**
   * @brief Mass of the MAV (kg)
   *
   * @param stage stage index.
   * @return double mass value.
   */
  double getMass(const int stage = 0) const;
  /**
   * @brief Desired position in world frame [x, y, z] (m)
   *
   * @param value desired_position value.
   * @param stage stage index, or -1 to apply to all stages.
   */
  void setDesiredPosition(const std::array<double, desired_position_length>& value,
                          const int stage = -1);

  /**
   * @brief Desired position in world frame [x, y, z] (m)
   *
   * @param stage stage index.
   * @return std::array<double, desired_position_length> desired_position value.
   */
  std::array<double, desired_position_length> getDesiredPosition(const int stage = 0) const;
  /**
   * @brief Desired orientation as a quaternion [qw, qx, qy, qz]
   *
   * @param value desired_orientation value.
   * @param stage stage index, or -1 to apply to all stages.
   */
  void setDesiredOrientation(const std::array<double, desired_orientation_length>& value,
                             const int stage = -1);

  /**
   * @brief Desired orientation as a quaternion [qw, qx, qy, qz]
   *
   * @param stage stage index.
   * @return std::array<double, desired_orientation_length> desired_orientation value.
   */
  std::array<double, desired_orientation_length> getDesiredOrientation(const int stage = 0) const;
  /**
   * @brief External force acting on the MAV in base frame [fx, fy, fz] (N)
   *
   * @param value external_force value.
   * @param stage stage index, or -1 to apply to all stages.
   */
  void setExternalForce(const std::array<double, external_force_length>& value,
                        const int stage = -1);

  /**
   * @brief External force acting on the MAV in base frame [fx, fy, fz] (N)
   *
   * @param stage stage index.
   * @return std::array<double, external_force_length> external_force value.
   */
  std::array<double, external_force_length> getExternalForce(const int stage = 0) const;
  /**
   * @brief Stage gains for [x, y, z, roll, pitch, yaw, vx, vy, vz]
   *
   * @param value Q value.
   * @param stage stage index, or -1 to apply to all stages.
   */
  void setQ(const std::array<double, Q_length>& value, const int stage = -1);

  /**
   * @brief Stage gains for [x, y, z, roll, pitch, yaw, vx, vy, vz]
   *
   * @param stage stage index.
   * @return std::array<double, Q_length> Q value.
   */
  std::array<double, Q_length> getQ(const int stage = 0) const;
  /**
   * @brief Terminal gains for [x, y, z, roll, pitch, yaw, vx, vy, vz]
   *
   * @param value Qe value.
   * @param stage stage index, or -1 to apply to all stages.
   */
  void setQe(const std::array<double, Qe_length>& value, const int stage = -1);

  /**
   * @brief Terminal gains for [x, y, z, roll, pitch, yaw, vx, vy, vz]
   *
   * @param stage stage index.
   * @return std::array<double, Qe_length> Qe value.
   */
  std::array<double, Qe_length> getQe(const int stage = 0) const;
  /**
   * @brief Stage gains for control inputs [thrust, wx, wy, wz]
   *
   * @param value R value.
   * @param stage stage index, or -1 to apply to all stages.
   */
  void setR(const std::array<double, R_length>& value, const int stage = -1);

  /**
   * @brief Stage gains for control inputs [thrust, wx, wy, wz]
   *
   * @param stage stage index.
   * @return std::array<double, R_length> R value.
   */
  std::array<double, R_length> getR(const int stage = 0) const;
};

/**
 * @brief SoftStateBounds
 *
 * Soft state bounds lsbx and usbx for the MPC.
 */
struct SoftStateBounds {
  static constexpr size_t Nsbx = MPC_POSITION_NSBX;
  std::array<double, MPC_POSITION_NSBX> lsbx;
  std::array<double, MPC_POSITION_NSBX> usbx;

  /**
   * @brief Constructor
   */
  SoftStateBounds();

  /**
   * @brief Get the lsbx array
   *
   * @return double* lsbx.
   */
  double* getLsbx();

  /**
   * @brief Get the lsbx array
   *
   * @return const double* lsbx.
   */
  const double* getLsbx() const;

  /**
   * @brief Get the lsbx array
   *
   * @return std::array<double, MPC_POSITION_NSBX> lsbx.
   */
  std::array<double, MPC_POSITION_NSBX> getLsbxArray() const;

  /**
   * @brief Get the usbx array
   *
   * @return double* usbx.
   */
  double* getUsbx();

  /**
   * @brief Get the usbx array
   *
   * @return const double* usbx.
   */
  const double* getUsbx() const;

  /**
   * @brief Get the usbx array
   *
   * @return std::array<double, MPC_POSITION_NSBX> usbx.
   */
  std::array<double, MPC_POSITION_NSBX> getUsbxArray() const;

  /**
   * @brief Set the bounds
   *
   * @param bounds bounds.
   */
  void setBounds(const SoftStateBounds& bounds);

  /**
   * @brief Set the lsbx
   *
   * @param lsbx lsbx.
   */
  void setLsbx(const std::array<double, MPC_POSITION_NSBX>& lsbx);

  /**
   * @brief Set the lsbx at index
   *
   * @param index index.
   * @param value value.
   */
  void setLsbx(const int index, const double value);

  /**
   * @brief Set the usbx
   *
   * @param usbx usbx.
   */
  void setUsbx(const std::array<double, MPC_POSITION_NSBX>& usbx);

  /**
   * @brief Set the usbx at index
   *
   * @param index index.
   * @param value value.
   */
  void setUsbx(const int index, const double value);
};

/**
 * @brief SlackWeights
 *
 * Slack weights Zl, Zu, zl, zu for the MPC soft constraints.
 */
struct SlackWeights {
  static constexpr size_t Ns = MPC_POSITION_NS;
  std::array<double, MPC_POSITION_NS> Zl;  // Diagonal Hessian weights for lower slack variables
  std::array<double, MPC_POSITION_NS> Zu;  // Diagonal Hessian weights for upper slack variables
  std::array<double, MPC_POSITION_NS> zl;  // Linear weights for lower slack variables
  std::array<double, MPC_POSITION_NS> zu;  // Linear weights for upper slack variables

  /**
   * @brief Constructor
   */
  SlackWeights();

  /**
   * @brief Get the Zl array
   *
   * @return double* Zl.
   */
  double* getZl();

  /**
   * @brief Get the Zl array
   *
   * @return const double* Zl.
   */
  const double* getZl() const;

  /**
   * @brief Get the Zl array
   *
   * @return std::array<double, MPC_POSITION_NS> Zl.
   */
  std::array<double, MPC_POSITION_NS> getZlArray() const;

  /**
   * @brief Get the Zu array
   *
   * @return double* Zu.
   */
  double* getZu();

  /**
   * @brief Get the Zu array
   *
   * @return const double* Zu.
   */
  const double* getZu() const;

  /**
   * @brief Get the Zu array
   *
   * @return std::array<double, MPC_POSITION_NS> Zu.
   */
  std::array<double, MPC_POSITION_NS> getZuArray() const;

  /**
   * @brief Get the zl array
   *
   * @return double* zl.
   */
  double* getzl();

  /**
   * @brief Get the zl array
   *
   * @return const double* zl.
   */
  const double* getzl() const;

  /**
   * @brief Get the zl array
   *
   * @return std::array<double, MPC_POSITION_NS> zl.
   */
  std::array<double, MPC_POSITION_NS> getzlArray() const;

  /**
   * @brief Get the zu array
   *
   * @return double* zu.
   */
  double* getzu();

  /**
   * @brief Get the zu array
   *
   * @return const double* zu.
   */
  const double* getzu() const;

  /**
   * @brief Get the zu array
   *
   * @return std::array<double, MPC_POSITION_NS> zu.
   */
  std::array<double, MPC_POSITION_NS> getzuArray() const;

  /**
   * @brief Set the weights
   *
   * @param weights weights.
   */
  void setWeights(const SlackWeights& weights);

  /**
   * @brief Set the Zl
   *
   * @param Zl Zl.
   */
  void setZl(const std::array<double, MPC_POSITION_NS>& Zl);

  /**
   * @brief Set the Zl at index
   *
   * @param index index.
   * @param value value.
   */
  void setZl(const int index, const double value);

  /**
   * @brief Set the Zu
   *
   * @param Zu Zu.
   */
  void setZu(const std::array<double, MPC_POSITION_NS>& Zu);

  /**
   * @brief Set the Zu at index
   *
   * @param index index.
   * @param value value.
   */
  void setZu(const int index, const double value);

  /**
   * @brief Set the zl
   *
   * @param zl zl.
   */
  void setzl(const std::array<double, MPC_POSITION_NS>& zl);

  /**
   * @brief Set the zl at index
   *
   * @param index index.
   * @param value value.
   */
  void setzl(const int index, const double value);

  /**
   * @brief Set the zu
   *
   * @param zu zu.
   */
  void setzu(const std::array<double, MPC_POSITION_NS>& zu);

  /**
   * @brief Set the zu at index
   *
   * @param index index.
   * @param value value.
   */
  void setzu(const int index, const double value);
};

/**
 * @brief SlackWeightsEnd
 *
 * Slack weights Zl_e, Zu_e, zl_e, zu_e for the terminal MPC soft constraints.
 */
struct SlackWeightsEnd {
  static constexpr size_t Ns_e = MPC_POSITION_NS;
  std::array<double, MPC_POSITION_NS> Zl_e;  // Diagonal Hessian weights for lower slack variables
  std::array<double, MPC_POSITION_NS> Zu_e;  // Diagonal Hessian weights for upper slack variables
  std::array<double, MPC_POSITION_NS> zl_e;  // Linear weights for lower slack variables
  std::array<double, MPC_POSITION_NS> zu_e;  // Linear weights for upper slack variables

  /**
   * @brief Constructor
   */
  SlackWeightsEnd();

  /**
   * @brief Get the Zl_e array
   *
   * @return double* Zl_e.
   */
  double* getZlE();

  /**
   * @brief Get the Zl_e array
   *
   * @return const double* Zl_e.
   */
  const double* getZlE() const;

  /**
   * @brief Get the Zl_e array
   *
   * @return std::array<double, MPC_POSITION_NS> Zl_e.
   */
  std::array<double, MPC_POSITION_NS> getZlEArray() const;

  /**
   * @brief Get the Zu_e array
   *
   * @return double* Zu_e.
   */
  double* getZuE();

  /**
   * @brief Get the Zu_e array
   *
   * @return const double* Zu_e.
   */
  const double* getZuE() const;

  /**
   * @brief Get the Zu_e array
   *
   * @return std::array<double, MPC_POSITION_NS> Zu_e.
   */
  std::array<double, MPC_POSITION_NS> getZuEArray() const;

  /**
   * @brief Get the zl_e array
   *
   * @return double* zl_e.
   */
  double* getzlE();

  /**
   * @brief Get the zl_e array
   *
   * @return const double* zl_e.
   */
  const double* getzlE() const;

  /**
   * @brief Get the zl_e array
   *
   * @return std::array<double, MPC_POSITION_NS> zl_e.
   */
  std::array<double, MPC_POSITION_NS> getzlEArray() const;

  /**
   * @brief Get the zu_e array
   *
   * @return double* zu_e.
   */
  double* getzuE();

  /**
   * @brief Get the zu_e array
   *
   * @return const double* zu_e.
   */
  const double* getzuE() const;

  /**
   * @brief Get the zu_e array
   *
   * @return std::array<double, MPC_POSITION_NS> zu_e.
   */
  std::array<double, MPC_POSITION_NS> getzuEArray() const;

  /**
   * @brief Set the weights
   *
   * @param weights weights.
   */
  void setWeights(const SlackWeightsEnd& weights);

  /**
   * @brief Set the Zl_e
   *
   * @param Zl_e Zl_e.
   */
  void setZlE(const std::array<double, MPC_POSITION_NS>& Zl_e);

  /**
   * @brief Set the Zl_e at index
   *
   * @param index index.
   * @param value value.
   */
  void setZlE(const int index, const double value);

  /**
   * @brief Set the Zu_e
   *
   * @param Zu_e Zu_e.
   */
  void setZuE(const std::array<double, MPC_POSITION_NS>& Zu_e);

  /**
   * @brief Set the Zu_e at index
   *
   * @param index index.
   * @param value value.
   */
  void setZuE(const int index, const double value);

  /**
   * @brief Set the zl_e
   *
   * @param zl_e zl_e.
   */
  void setzlE(const std::array<double, MPC_POSITION_NS>& zl_e);

  /**
   * @brief Set the zl_e at index
   *
   * @param index index.
   * @param value value.
   */
  void setzlE(const int index, const double value);

  /**
   * @brief Set the zu_e
   *
   * @param zu_e zu_e.
   */
  void setzuE(const std::array<double, MPC_POSITION_NS>& zu_e);

  /**
   * @brief Set the zu_e at index
   *
   * @param index index.
   * @param value value.
   */
  void setzuE(const int index, const double value);
};

/**
 * @brief NonlinearConstraintBounds
 *
 * Lower and upper bounds lh and uh for nonlinear constraints h(x,u) at intermediate
 * shooting nodes (1 to N-1) and at the terminal node (N).
 */
struct NonlinearConstraintBounds {
  static constexpr size_t Nh = MPC_POSITION_NH;
  std::array<double, MPC_POSITION_NH> lh;
  std::array<double, MPC_POSITION_NH> uh;

  /**
   * @brief Constructor
   */
  NonlinearConstraintBounds();

  /**
   * @brief Get the lh array
   *
   * @return double* lh.
   */
  double* getLh();

  /**
   * @brief Get the lh array
   *
   * @return const double* lh.
   */
  const double* getLh() const;

  /**
   * @brief Get the lh array
   *
   * @return std::array<double, MPC_POSITION_NH> lh.
   */
  std::array<double, MPC_POSITION_NH> getLhArray() const;

  /**
   * @brief Get the uh array
   *
   * @return double* uh.
   */
  double* getUh();

  /**
   * @brief Get the uh array
   *
   * @return const double* uh.
   */
  const double* getUh() const;

  /**
   * @brief Get the uh array
   *
   * @return std::array<double, MPC_POSITION_NH> uh.
   */
  std::array<double, MPC_POSITION_NH> getUhArray() const;

  /**
   * @brief Set the bounds
   *
   * @param bounds bounds.
   */
  void setBounds(const NonlinearConstraintBounds& bounds);

  /**
   * @brief Set the lh
   *
   * @param lh lh.
   */
  void setLh(const std::array<double, MPC_POSITION_NH>& lh);

  /**
   * @brief Set the lh at index
   *
   * @param index index.
   * @param value value.
   */
  void setLh(const int index, const double value);

  /**
   * @brief Set the uh
   *
   * @param uh uh.
   */
  void setUh(const std::array<double, MPC_POSITION_NH>& uh);

  /**
   * @brief Set the uh at index
   *
   * @param index index.
   * @param value value.
   */
  void setUh(const int index, const double value);
};

/**
 * @brief SoftNonlinearConstraintBounds
 *
 * Lower and upper bounds lsh and ush for soft nonlinear constraints at
 * intermediate shooting nodes (1 to N-1) and at the terminal node (N).
 */
struct SoftNonlinearConstraintBounds {
  static constexpr size_t Nsh = MPC_POSITION_NSH;
  std::array<double, MPC_POSITION_NSH> lsh;
  std::array<double, MPC_POSITION_NSH> ush;

  /**
   * @brief Constructor
   */
  SoftNonlinearConstraintBounds();

  /**
   * @brief Get the lsh array
   *
   * @return double* lsh.
   */
  double* getLsh();

  /**
   * @brief Get the lsh array
   *
   * @return const double* lsh.
   */
  const double* getLsh() const;

  /**
   * @brief Get the lsh array
   *
   * @return std::array<double, MPC_POSITION_NSH> lsh.
   */
  std::array<double, MPC_POSITION_NSH> getLshArray() const;

  /**
   * @brief Get the ush array
   *
   * @return double* ush.
   */
  double* getUsh();

  /**
   * @brief Get the ush array
   *
   * @return const double* ush.
   */
  const double* getUsh() const;

  /**
   * @brief Get the ush array
   *
   * @return std::array<double, MPC_POSITION_NSH> ush.
   */
  std::array<double, MPC_POSITION_NSH> getUshArray() const;

  /**
   * @brief Set the bounds
   *
   * @param bounds bounds.
   */
  void setBounds(const SoftNonlinearConstraintBounds& bounds);

  /**
   * @brief Set the lsh
   *
   * @param lsh lsh.
   */
  void setLsh(const std::array<double, MPC_POSITION_NSH>& lsh);

  /**
   * @brief Set the lsh at index
   *
   * @param index index.
   * @param value value.
   */
  void setLsh(const int index, const double value);

  /**
   * @brief Set the ush
   *
   * @param ush ush.
   */
  void setUsh(const std::array<double, MPC_POSITION_NSH>& ush);

  /**
   * @brief Set the ush at index
   *
   * @param index index.
   * @param value value.
   */
  void setUsh(const int index, const double value);
};

}  // namespace acados_mpc

#endif  // ACADOS_MPC_ACADOS_MPC_DATATYPE_HPP_
